### ISSUE TITLE
possible 80X backports (terminated on 8_0_20)

### ISSUE THREAD

**Issue by slava77** [slava77/cmssw#93]
This contains possible backports that affect reco or miniAOD.

[updated Sept 9]: 

The following features were included in CMSSW_8_0_20 build, unless noted otherwise
- Affects only miniAOD:
    - [superseded] <strike>Fix posftix and scheduled mode issue in the runMETUncertainty tool https://github.com/cms-sw/cmssw/pull/14606 https://github.com/cms-sw/cmssw/pull/15616</strike> superseded by https://github.com/cms-sw/cmssw/pull/15600
    - [merged Sept 7] update the ecalLaserCorr filter for the 2016 https://github.com/cms-sw/cmssw/pull/15610
    - [merged Sept 7] Keep lumi from scalers https://github.com/cms-sw/cmssw/pull/15622
    - [merged Sept 7] Switching BoostedDoubleSV tagger to v3 training  https://github.com/cms-sw/cmssw/pull/15446
    - [merged Sept 7] Prevent negative jet smearing factor https://github.com/cms-sw/cmssw/pull/15250
    - [merged Sept 7] Save pixel and strip layers in miniAOD https://github.com/cms-sw/cmssw/pull/15641
    - [merged Sept 7] Backport of 81X PU jet ID https://github.com/cms-sw/cmssw/pull/15211
    - [merged Sept 9] Updating Puppi Photon to ignore photons with large eta and to add back candidates https://github.com/cms-sw/cmssw/pull/15429
        - based on RECO meeting discussion Sept 7, the essential features already confirmed to be OK will be split in a separate PR (or this PR will be updated to hold only main features related to puppi tuning)
    - [merged Sept 7] Puppi MET and MET significance fixes in the MET tool https://github.com/cms-sw/cmssw/pull/15600
    - [not for 8_0_20 release ⛔ ] <strike>Puppi isolation electrons and photons miniAOD <strike>https://github.com/cms-sw/cmssw/pull/15628</strike> https://github.com/cms-sw/cmssw/pull/15722</strike>
        - based on RECO meeting discussion Sept 7, this is late and is not considered essential.
    - [merged Sept 7] keep muon parents https://github.com/cms-sw/cmssw/pull/15742
    - [merged Sept 8] Extension of miniAOD event content to be able to run tau mva isolation discriminator on miniAOD input https://github.com/cms-sw/cmssw/pull/15758
        - [81X component] Extension of PAT TauPFEssential event content to be able to run anti-electron discriminators in miniAOD input https://github.com/cms-sw/cmssw/pull/15747
        - [81X component] Extension of miniAOD event content to be able to run tau mva isolation discriminator on miniAOD input  https://github.com/cms-sw/cmssw/pull/15731
    - [not for 8_0_20 release ⛔ ] <strike>MiniAOD: met filter flag on bad muon https://github.com/cms-sw/cmssw/pull/15762</strike>
        - based on RECO meeting discussion Sept 7, this is late and is not considered essential.
-Affects AOD, relevant only for data:
    - [merged Sept 7] Typo correction in config file (CSC halo) https://github.com/cms-sw/cmssw/pull/14539
- Affects AOD for MC and data:
    -  [merged Sept 7] Bugfix: Fake muon tracks become charged hadrons in PF  https://github.com/cms-sw/cmssw/pull/14669 (has to be a part of reco, can not be rerun from AOD)
    - [merged Sept 7] btag HIP mitigation + ctag bugfix  https://github.com/cms-sw/cmssw/pull/15601 (can be rerun from AOD)
    - [merged Sept 7] fix nan Calo-towers, when HO is deactivated, but has energy deposit https://github.com/cms-sw/cmssw/pull/15706 (this change is essentially purely technical: no downstream reco physics objects are affected)

HLT performance speedups affecting reco: included in CMSSW_8_0_19
- #15280 — HLT seeding speed-up
- #15287 — PF block algo speed-up
- #15288 — Pixel track reco improvements
- #15294 — PFRecHit slimming & eta/phi computation speed-up
- #15295 — StripCPE & tracking improvements

**Comment by cvuosalo** [comment]
15250 — Prevent negative jet smearing
 15446 — Boosted double SV tagger v3 training
 HLT performance speed-ups:
15280 — HLT seeding speed-up
15287 — PF block algo speed-up
15288 — Pixel track reco improvements
15294 — PFRecHit slimming & eta/phi computation speed-up
15295 — StripCPE & tracking improvements

**Comment by cvuosalo** [comment]
What about #14764 (and #14763 for 81X)? Should it ever go into 80X?

**Comment by cvuosalo** [comment]
MET list:
https://indico.cern.ch/event/562813/contributions/2274096/attachments/1326663/1991821/PRforMET.pdf

**Comment by ferencek** [comment]
Also adding to the list
#15601 — btag HIP mitigation + ctag bugfix

**Comment by davidlange6** [comment]
#14764 as it is does not affect AOD (which is one of its problems)

**Comment by davidlange6** [comment]
The HLT speed ups are now merged.

**Comment by davidlange6** [comment]
MET list is to back port 
https://github.com/cms-sw/cmssw/pull/15565 [not yet in 81x]
https://github.com/cms-sw/cmssw/pull/15562 [in 81x]
https://github.com/cms-sw/cmssw/pull/14608 [in 81x]
https://github.com/cms-sw/cmssw/pull/14538 [in 81x, trivial in terms of code]
https://github.com/cms-sw/cmssw/pull/14670 [in 81x, trivial in terms of code]
(+ potentially 3 other PRs not yet made)

**Comment by slava77** [comment]
Backports here will not be enforced to leave the default performance unchanged.
@davidlange6 please correct, if it should be done otherwise.

New era will be needed in prompt reco.

**Comment by slava77** [comment]
https://github.com/cms-sw/cmssw/pull/15568 may need to be backported as well ... not sure yet (the issue came up through HLT use)

**Comment by slava77** [comment]
I have updated the list in the issue description (the top-most field https://github.com/slava77/cmssw/issues/93#issue-157283069)

@mariadalfonso do we have all the MET PRs submitted already? From your slides in reco meeting, it looks like some are not there yet.

**Comment by slava77** [comment]
the list was updated (see the issue description)
- several PRs are now signed
- backport for caloTowers is added https://github.com/cms-sw/cmssw/pull/15706

**Comment by slava77** [comment]
the list was updated (see the issue description)

- added Puppi isolation electrons and photons miniAOD https://github.com/cms-sw/cmssw/pull/15628

**Comment by roger-wolf** [comment]
Dear all, 

we have two 81X pull requests to be expected still by tomorrow (80X backport asap shortly after) for potentially two items:

1) extension of miniAOD content to be able to re-calculate Tau-ID (isolation) MVA from miniAOD;
2) the same for the re-calulcation on the anti-electron MVA (if it arrives in time).

These will be crucial for the TauPOG project to be able to re-calculate these high-level discriminators on miniAOD. The changes to the miniAOD event content are anticipated to be minimal on the event content and event size. They will still require a discussion in the XPOG meeting on Tuesday.

The PR's will be followed by PR's to set up the infrastructure to actually do the re-calculation on the minAOD (already available for 1), for 2) expected to arrive within the next 1-2 days). 

I'll add the PR's to this thread asa available tomorrow. 

Cheers,
Roger

**Comment by slava77** [comment]
On 9/4/16 4:52 PM, Roger Wolf wrote:
> Dear all,
> 
> we have two 81X pull requests to be expected still by tomorrow (80X
> backport asap shortly after) for potentially two items:
> 
> 1) extension of miniAOD content to be able to re-calculate Tau-ID
> (isolation) MVA from miniAOD;
> 2) the same for the re-calulcation on the anti-electron MVA (if it
> arrives in time).
> 
> These will be crucial for the TauPOG project to be able to re-calculate
> these high-level discriminators on miniAOD. The changes to the miniAOD
> event content are anticipated to be minimal on the event content and
> event size. They will still require a discussion in the XPOG meeting on
> Tuesday.
> 
> The PR's will be followed by PR's to set up the infrastructure to
> actually do the re-calculation on the minAOD (already available for 1),
> for 2) expected to arrive within the next 1-2 days).
> 
> I'll add the PR's to this thread asa available tomorrow.
> 

OK, I will update the list once the PRs are available.

**Comment by slava77** [comment]
the list was updated (see the issue description)
- cms-sw#15628 was replaced by cms-sw#15722
- tau PR cms-sw#15731 added

**Comment by slava77** [comment]
the list is updated:
- added "keep muon parents" cms-sw#15742 
- added https://github.com/cms-sw/cmssw/pull/15747

**Comment by davidlange6** [comment]
These are now merged in the 80x 1100 IB to start in 5 minutes
cms-sw#14669
cms-sw#14539
cms-sw#15641
cms-sw#15742
cms-sw#15706
cms-sw#15250
cms-sw#15610
cms-sw#15446
cms-sw#15601
cms-sw#15600
cms-sw#15211

Missing still
https://github.com/cms-sw/cmssw/pull/15429
back port of https://github.com/cms-sw/cmssw/pull/15741 (looks like this one is too late)
back port of https://github.com/cms-sw/cmssw/pull/15731
back port of https://github.com/cms-sw/cmssw/pull/15747

anything else we need to include in 8_0_20 for data re-reco?
anything that I should not have included?

@slava77 @cvuosalo @roger-wolf @gpetruc

**Comment by roger-wolf** [comment]
Hi all, 

I'm on  https://github.com/cms-sw/cmssw/pull/15747 now. It should be ready within the next few hours. 

Cheers,
Roger

**Comment by slava77** [comment]
I have updated the status in the PR description

**Comment by slava77** [comment]
@davidlange6 
you missed to list cms-sw#15622 as merged.

- cms-sw#15429 puppi photon MET:  should hopefully converge today. If the feature misses the release, the objects can be redone from miniAOD.
- cms-sw#15741 puppi isolations in pat egamma: this did not converge, if I'm not mistaken, the (non)functional parts of the PR are the same as last week.
- the two tau PRs are expected and appear rather important to allow rerunning from miniAOD.

**Comment by slava77** [comment]
updated with notes following RECO meeting and newly available backport numbers for tau PR

**Comment by slava77** [comment]
updated with included features.
The CMSSW_8_0_20 release build is now in progress.

**Comment by slava77** [comment]
Closing this.
Another similar issue is open now https://github.com/cms-sw/cmssw/issues/16177
